package eu.hxreborn.phdp.ui.state

import eu.hxreborn.phdp.prefs.Prefs
import eu.hxreborn.phdp.prefs.RotationOffsets
import eu.hxreborn.phdp.ui.theme.DarkThemeConfig

data class PrefsState(
    val enabled: Boolean = Prefs.enabled.default,
    val color: Int = Prefs.color.default,
    val strokeWidth: Float = Prefs.strokeWidth.default,
    val ringGap: Float = Prefs.ringGap.default,
    val opacity: Int = Prefs.opacity.default,
    val hooksFeedback: Boolean = Prefs.hooksFeedback.default,
    val clockwise: Boolean = Prefs.clockwise.default,
    val progressEasing: String = Prefs.progressEasing.default,
    val errorColor: Int = Prefs.errorColor.default,
    val strokeCapStyle: String = Prefs.strokeCapStyle.default,
    val backgroundRingEnabled: Boolean = Prefs.backgroundRingEnabled.default,
    val backgroundRingColor: Int = Prefs.backgroundRingColor.default,
    val backgroundRingOpacity: Int = Prefs.backgroundRingOpacity.default,
    val glowEnabled: Boolean = Prefs.glowEnabled.default,
    val glowRadius: Float = Prefs.glowRadius.default,
    val powerSaverMode: String = Prefs.powerSaverMode.default,
    val showDownloadCount: Boolean = Prefs.showDownloadCount.default,
    val badgeOffsets: RotationOffsets = RotationOffsets.EMPTY,
    val badgeTextSize: Float = Prefs.badgeTextSize.default,
    val finishStyle: String = Prefs.finishStyle.default,
    val finishHoldMs: Int = Prefs.finishHoldMs.default,
    val finishExitMs: Int = Prefs.finishExitMs.default,
    val finishUseFlashColor: Boolean = Prefs.finishUseFlashColor.default,
    val finishFlashColor: Int = Prefs.finishFlashColor.default,
    val minVisibilityEnabled: Boolean = Prefs.minVisibilityEnabled.default,
    val minVisibilityMs: Int = Prefs.minVisibilityMs.default,
    val completionPulseEnabled: Boolean = Prefs.completionPulseEnabled.default,
    val percentTextEnabled: Boolean = Prefs.percentTextEnabled.default,
    val percentTextPosition: String = Prefs.percentTextPosition.default,
    val percentTextOffsets: RotationOffsets = RotationOffsets.EMPTY,
    val percentTextSize: Float = Prefs.percentTextSize.default,
    val filenameTextEnabled: Boolean = Prefs.filenameTextEnabled.default,
    val filenameTextPosition: String = Prefs.filenameTextPosition.default,
    val filenameTextOffsets: RotationOffsets = RotationOffsets.EMPTY,
    val filenameTextSize: Float = Prefs.filenameTextSize.default,
    val filenameMaxChars: Int = Prefs.filenameMaxChars.default,
    val filenameTruncateEnabled: Boolean = Prefs.filenameTruncateEnabled.default,
    val percentTextBold: Boolean = Prefs.percentTextBold.default,
    val percentTextItalic: Boolean = Prefs.percentTextItalic.default,
    val filenameTextBold: Boolean = Prefs.filenameTextBold.default,
    val filenameTextItalic: Boolean = Prefs.filenameTextItalic.default,
    val filenameEllipsize: String = Prefs.filenameEllipsize.default,
    val filenameVerticalText: Boolean = Prefs.filenameVerticalText.default,
    val previewFilenameText: String = Prefs.previewFilenameText.default,
    val darkThemeConfig: DarkThemeConfig = DarkThemeConfig.FOLLOW_SYSTEM,
    val useDynamicColor: Boolean = Prefs.useDynamicColor.default,
    val ringScaleX: Float = Prefs.ringScaleX.default,
    val ringScaleY: Float = Prefs.ringScaleY.default,
    val ringScaleLinked: Boolean = Prefs.ringScaleLinked.default,
    val ringOffsetX: Float = Prefs.ringOffsetX.default,
    val ringOffsetY: Float = Prefs.ringOffsetY.default,
    val pathMode: Boolean = Prefs.pathMode.default,
    val selectedPackages: Set<String> = Prefs.selectedPackages.default,
    val showSystemPackages: Boolean = Prefs.showSystemPackages.default,
)
